name = "SpacecraftDynamics"
uuid = "cc5c844c-0595-4d2f-9df6-d129cc96db37"
authors = ["BennetOutland <bennet.outland@pm.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
