name = "SpacecraftDynamics"
uuid = "cc5c844c-0595-4d2f-9df6-d129cc96db37"
authors = ["BennetOutland <bennet.outland@pm.me> and contributors"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DifferentialEquations = "7.17.0"
LinearAlgebra = "1.11.0"
Revise = "3.13.2"
Rotations = "1.7.1"
SatelliteToolbox = "1.0.0"
StaticArrays = "1.9.16"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
